### ISSUE TITLE
Absolutely unclear on how to get the battery indicator to work

### ISSUE THREAD

**Issue by KTibow** [Fr4nKB/Glyphify#37]
I'm trying to get the battery indicator to work on my 2a and it's been an absolutely frustrating experience. The app gives a barrage of pop ups every time it's launched, and there's no documentation in the README or in the app on how to enable it. I believe I've done everything I need to but it just doesn't show up.

**Comment by Fr4nKB** [comment]
Battery indicator starts automatically on v1.4.2 if you have a 2a (not 2a plus since the GDK doesn't support it yet) and the phone is connected to power, then you need to wiggle your phone to display it.

**There have been some changes lately that impose the use of glyph debug mode, be sure that's on and reboot your device.**

**Comment by KTibow** [comment]
update: works on second download :+1:
(although it's a bit glitchy, it keeps reanimating out of nowhere, maybe it thinks that me typing on my desk is a "wiggle"?)

**Comment by Fr4nKB** [comment]
Nice!
Yes that can be the case, I've tried to match the sensitivity used by Nothing in their other phones and on my Phone(2) the same thing happens
